name: Install-PSResource-cmdlet
run-name: ${{ github.workflow }} [${{ github.ref_name }}]

on:
  workflow_dispatch:

jobs:
  install-and-list-modules:
    runs-on: ubuntu-22.04
    steps:
      - name: Install newer PSResourceGet
        shell: pwsh
        run: |
          Install-Module -Name Microsoft.PowerShell.PSResourceGet -Force

      - name: List Available Modules
        shell: pwsh
        run: |
          Get-Module -ListAvailable | Select-Object Version, Name | Sort-Object Name
          
      - name: Install Modules
        shell: pwsh
        run: |
          Import-Module Microsoft.PowerShell.PSResourceGet -Force
          Install-PSResource -TrustRepository -RequiredResource  @{
            Az = @{
              version = '[12.0.0,12.1.0]'
              repository = 'PSGallery'
            }
            dbatools = @{
              version = '[2.10.0,2.14.0]'
              repository = 'PSGallery'
            }
          }

      - name: List Available Modules
        shell: pwsh
        run: |
          Get-Module -ListAvailable | Select-Object Version, Name | Sort-Object Name
