name: ModuleFast
run-name: ${{ github.workflow }} [${{ github.ref_name }}]

on:
  workflow_dispatch:

jobs:
  install-and-list-modules:
    runs-on: ubuntu-22.04
    steps:
      - name: ⚡ ModuleFast with Specification
        uses: JustinGrote/ModuleFast-action@v0.0.1
        with:
          specification: |
            Microsoft365DSC=1.24.1002.1
            Az.Accounts=3.0.2
            Az.ResourceGraph=1.0.0
            Az.Resources=7.2.0
            Az.ResourceGraph=1.0.0
            Az.SecurityInsights=3.1.2
            DSCParser=2.0.0.10
            ExchangeOnlineManagement=3.4.0
            Microsoft.Graph.Applications=2.23.0
            Microsoft.Graph.Beta.Applications=2.23.0
            Microsoft.Graph.Authentication=2.23.0
            Microsoft.Graph.Beta.DeviceManagement=2.23.0
            Microsoft.Graph.Beta.Devices.CorporateManagement=2.23.0
            Microsoft.Graph.Beta.DeviceManagement.Administration=2.23.0
            Microsoft.Graph.Beta.DeviceManagement.Enrollment=2.23.0
            Microsoft.Graph.Beta.Identity.DirectoryManagement=2.23.0
            Microsoft.Graph.Beta.Identity.Governance=2.23.0
            Microsoft.Graph.Beta.Identity.SignIns=2.23.0
            Microsoft.Graph.Beta.Reports=2.23.0
            Microsoft.Graph.Beta.Search=2.23.0
            Microsoft.Graph.Beta.Teams=2.23.0
            Microsoft.Graph.DeviceManagement.Administration=2.23.0
            Microsoft.Graph.Beta.DirectoryObjects=2.23.0
            Microsoft.Graph.Groups=2.23.0
            Microsoft.Graph.Beta.Groups=2.23.0
            Microsoft.Graph.Planner=2.23.0
            Microsoft.Graph.Sites=2.23.0
            Microsoft.Graph.Users=2.23.0
            Microsoft.Graph.Users.Actions=2.23.0
            Microsoft.PowerApps.Administration.PowerShell=2.0.191
            MicrosoftTeams=6.5.0
            MSCloudLoginAssistant=1.1.25
            PnP.PowerShell=1.12.0
            ReverseDSC=2.0.0.20
          
      - name: List Available Modules
        shell: pwsh
        run: |
          Get-Module -ListAvailable | Select-Object Version, Name | Sort-Object Name
