name: ModuleFast-scriptblock
run-name: ${{ github.workflow }} [${{ github.ref_name }}]

on:
  workflow_dispatch:

jobs:
  install-and-list-modules:
    runs-on: ubuntu-22.04
    steps:
      - name: Test
        shell: pwsh
        run: |
          & ([scriptblock]::Create((iwr 'https://github.com/JustinGrote/ModuleFast/releases/latest/download/ModuleFast.ps1'))) -Specification 'Az=12.1.0','dbatools=2.1.14'
          
      - name: List Available Modules
        shell: pwsh
        run: |
          Get-Module -ListAvailable | Select-Object Version, Name | Sort-Object Name
