name: ModuleFast
run-name: ${{ github.workflow }} [${{ github.ref_name }}]

on:
  workflow_dispatch:

jobs:
  install-and-list-modules:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: ⚡ ModuleFast with Specification
        uses: JustinGrote/ModuleFast-action@v0.0.1
        with:
          path: './modules.requires.psd1'
          
      - name: List Available Modules
        shell: pwsh
        run: |
          Get-Module -ListAvailable | Select-Object Version, Name | Sort-Object Name
