name: psmodulecache
run-name: ${{ github.workflow }} [${{ github.ref_name }}]

on:
  workflow_dispatch:

jobs:
  install-and-list-modules:
    runs-on: ubuntu-22.04
    steps:
      - name: Install and cache PowerShell modules
        uses: potatoqualitee/psmodulecache@v6.2
        with:
          modules-to-cache: Az:12.1.0, dbatools:2.1.14, Microsoft.Graph:2.0.0
          
      - name: List Available Modules
        shell: pwsh
        run: |
          Get-Module -ListAvailable | Select-Object Version, Name | Sort-Object Name
