on:
  workflow_dispatch:
    inputs:
      print_azcopy_log:
        type: boolean
        description: 'Print azcopy log?'
        default: false
      add_network_rule:
        type: boolean
        description: 'Add network rule?'
        default: true

name: Sync FileShare to Blob

permissions:
  id-token: write

env:
  AZURE_RESOURCE_GROUP: rg-fs-blob-sync
  AZURE_STORAGE_ACCOUNT: stfsblobsync
  AZURE_CONTAINER_NAME: pics
  AZURE_FILESHARE_NAME: pics
  NETWORK_RULE: true

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:

    - name: Azure Login
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: Add network rule
      id: runner_ip
      if: inputs.add_network_rule == true
      run: |
        ADDR=$(curl -k "https://checkip.amazonaws.com")
        az storage account network-rule add --account-name $AZURE_STORAGE_ACCOUNT --resource-group $AZURE_RESOURCE_GROUP --ip-address $ADDR > /dev/null
        #az storage account update --resource-group $AZURE_RESOURCE_GROUP --name $AZURE_STORAGE_ACCOUNT --default-action Allow > /dev/null
        echo "Waiting for 3 seconds..." ; sleep 1s
        echo "Waiting for 2 seconds..." ; sleep 1s
        echo "Waiting for 1 seconds..." ; sleep 1s

    - name: azcopy fileshare to blob container
      #env:
        #AZCOPY_AUTO_LOGIN_TYPE: MSI
        #AZCOPY_MSI_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
        #AZCOPY_AUTO_LOGIN_TYPE: AZCLI # This is the auto login type you want
        #AZCOPY_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }} # Don't forget this
      shell: pwsh
      run: |
        echo ""
        $expiry = (Get-Date).AddMinutes(3).ToString('yyyy-MM-ddTHH:mm:ssZ')
        $allowedServices = (@('blob','file') | ForEach-Object { $_[0] }) -join ''
        $allowedResourceTypes = (@('container','object') | ForEach-Object { $_[0] }) -join ''
        $allowedPermissions = (@('read','write','delete','list','add','create') | ForEach-Object { $_[0] }) -join ''
        # $sas = az storage account generate-sas --account-name stfsblobsync --permissions rwdlac --resource-types co --services fb --expiry (Get-Date).AddMinutes(3).ToString('yyyy-MM-ddTHH:mm:ssZ') -o tsv
        $sas = az storage account generate-sas --account-name $env:AZURE_STORAGE_ACCOUNT --permissions $allowedPermissions --resource-types $allowedResourceTypes --services $allowedServices --expiry $expiry -o tsv
        $source = "https://{0}.file.core.windows.net/{1}?{2}" -f $env:AZURE_STORAGE_ACCOUNT, $env:AZURE_FILESHARE_NAME, $sas
        $destination = "https://{0}.blob.core.windows.net/{1}?{2}" -f $env:AZURE_STORAGE_ACCOUNT, $env:AZURE_CONTAINER_NAME, $sas
        # azcopy copy $source $destination --recursive=true --overwrite=ifSourceNewer
        azcopy sync $source $destination --recursive=true --delete-destination=true

    - name: Print logs
      if: inputs.print_azcopy_log == true
      run: cat /home/runner/.azcopy/*.log

    - name: Remove network rule
      if: steps.runner_ip.outcome == 'success'
      run: |
        az storage account network-rule remove --account-name $AZURE_STORAGE_ACCOUNT --resource-group $AZURE_RESOURCE_GROUP --ip-address ${{ steps.runner_ip.ADDR }} > /dev/null
        #az storage account update --resource-group $AZURE_RESOURCE_GROUP --name $AZURE_STORAGE_ACCOUNT --default-action Deny > /dev/null
        

